GET http://localhost:5000/test

###
POST http://localhost:5000/auth/sign
Content-Type: application/json

{
    "email": "ale.lacayo@somedomain.com",
    "password": "pescadito04",
    "appKey": "doggoservice"
}

###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email": "ale.lacayo@somedomain.com",
    "password": "pescadito04",
    "name": "Alexandra Lacayo",
    "appKey": "doggoservice"
}
